import { images } from "./index";

export const featuredMenu = [
  {
    name: "Chicken Fry Piece Biryani (Boneless)",
    desc: "Crispy fried chicken pieces layered into slow-dum basmati. The best of both worlds on one plate.",
    type: "non-veg",
    category: "biryani",
    img: images.bonelss,
    price: 219,
  },
  {
    name: "Mutton Dum Biryani",
    desc: "Tender mutton slow-cooked under a sealed dum with whole spices and fragrant long-grain rice.",
    type: "non-veg",
    category: "biryani",
    img: images.mutton,
    price: 279,
  },
  {
    name: "Karvepaku Chicken",
    desc: "Curry-leaf tossed chicken with a crisp, aromatic finish — a regional favourite done right.",
    type: "non-veg",
    category: "curries",
    img: images.karivepaku,
    price: 199,
  },
  {
    name: "Chicken Tikka",
    desc: "Marinated overnight and roasted in the tandoor. Juicy inside, lightly charred outside.",
    type: "non-veg",
    category: "tandoori",
    img: images.tikka,
    price: 249,
  },
  {
    name: "Paneer Tikka",
    desc: "Cottage cheese marinated in spiced yoghurt, skewered and fired in the tandoor until golden.",
    type: "veg",
    category: "tandoori",
    img: images.panner_tikka,
    price: 249,
  },
  {
    name: "Butter Chicken Masala",
    desc: "Slow-simmered chicken in a velvety tomato-butter sauce. Rich, mild, and endlessly satisfying.",
    type: "non-veg",
    category: "curries",
    img: images.butterchickenmasal,
    price: 209,
  },
];

export const extraMenu = [
  {
    name: "Chicken Dum Biryani",
    desc: "The classic. Whole-spice dum with bone-in chicken and saffron-tinged basmati.",
    type: "non-veg",
    category: "biryani",
    img: images.biriyani,
    price: 199,
  },
  {
    name: "Gunpowder Chicken",
    desc: "Fiery dry-tossed chicken coated in a bold gunpowder spice blend. Not for the faint-hearted.",
    type: "non-veg",
    category: "indo-chinese",
    img: images.chickenKebab || images.biriyani,
    price: 199,
  },
  {
    name: "Honey Chilli Chicken",
    desc: "Crispy chicken glazed in a sweet-heat honey chilli sauce — an Indo-Chinese crowd-pleaser.",
    type: "non-veg",
    category: "indo-chinese",
    img: images.dragonChicken || images.biriyani,
    price: 239,
  },
  {
    name: "Drums Of Heaven",
    desc: "Crispy chicken winglets tossed in a fiery, sticky sauce. The table empties these fast.",
    type: "non-veg",
    category: "indo-chinese",
    img: images.chickenKebab || images.biriyani,
    price: 269,
  },
  {
    name: "Paneer Butter Masala",
    desc: "Cottage cheese in a rich tomato-butter gravy — the vegetarian answer to butter chicken.",
    type: "veg",
    category: "curries",
    img: images.paneerTikka || images.biriyani,
    price: 199,
  },
  {
    name: "Kadai Paneer",
    desc: "Paneer and peppers stir-fried in a rustic kadai masala with whole spices and fresh coriander.",
    type: "veg",
    category: "curries",
    img: images.paneerTikka || images.biriyani,
    price: 189,
  },
  {
    name: "Mushroom Tikka Masala",
    desc: "Tandoor-kissed mushrooms folded into a spiced, creamy masala gravy.",
    type: "veg",
    category: "tandoori",
    img: images.mushroomBiryani || images.biriyani,
    price: 169,
  },
  {
    name: "Chicken Tikka Masala",
    desc: "Tandoori chicken pieces finished in a bold, spiced masala — smoky and deeply flavoured.",
    type: "non-veg",
    category: "tandoori",
    img: images.chickenTikka || images.biriyani,
    price: 229,
  },
  {
    name: "Gobi Manchurian",
    desc: "Crispy cauliflower florets tossed in a tangy Indo-Chinese sauce with ginger and spring onions.",
    type: "veg",
    category: "indo-chinese",
    img: images.vegManchurian || images.biriyani,
    price: 119,
  },
  {
    name: "Karvepaku Mushroom",
    desc: "Curry-leaf tossed mushrooms with the same bold regional treatment as the chicken version.",
    type: "veg",
    category: "curries",
    img: images.mushroomBiryani || images.biriyani,
    price: 169,
  },
  {
    name: "Chicken Achari Tikka",
    desc: "Pickle-spiced chicken skewers straight from the tandoor — tangy, smoky and sharp.",
    type: "non-veg",
    category: "tandoori",
    img: images.chickenTikka || images.biriyani,
    price: 259,
  },
  {
    name: "Chicken Malai Tikka",
    desc: "Cream-marinated chicken tikka with a sweeter, gentler flavour. Melt-in-the-mouth texture.",
    type: "non-veg",
    category: "tandoori",
    img: images.chickenTikka || images.biriyani,
    price: 269,
  },
];

export const allMenuItems = [...featuredMenu, ...extraMenu];
